import type { CountryCodes } from './types';

export const countries: CountryCodes = {
    AE: 'United Arab Emirates',
    AG: 'Antigua and Barbuda',
    AI: 'Anguilla',
    AL: 'Albania',
    AM: 'Armenia',
    AO: 'Angola',
    AR: 'Argentina',
    AT: 'Austria',
    AU: 'Australia',
    AZ: 'Azerbaijan',
    BB: 'Barbados',
    BE: 'Belgium',
    BF: 'Burkina-Faso',
    BG: 'Bulgaria',
    BH: 'Bahrain',
    BJ: 'Benin',
    BM: 'Bermuda',
    BN: 'Brunei Darussalam',
    BO: 'Bolivia',
    BR: 'Brazil',
    BS: 'Bahamas',
    BT: 'Bhutan',
    BW: 'Botswana',
    BY: 'Belarus',
    BZ: 'Belize',
    CA: 'Canada',
    CG: 'Democratic Republic of the Congo',
    CH: 'Switzerland',
    CL: 'Chile',
    CN: 'China',
    CO: 'Colombia',
    CR: 'Costa Rica',
    CV: 'Cape Verde',
    CY: 'Cyprus',
    CZ: 'Czech Republic',
    DE: 'Germany',
    DK: 'Denmark',
    DM: 'Dominica',
    DO: 'Dominican Republic',
    DZ: 'Algeria',
    EC: 'Ecuador',
    EE: 'Estonia',
    EG: 'Egypt',
    ES: 'Spain',
    FI: 'Finland',
    FJ: 'Fiji',
    FM: 'Federated States of Micronesia',
    FR: 'France',
    GB: 'Great Britain',
    GD: 'Grenada',
    GH: 'Ghana',
    GM: 'Gambia',
    GR: 'Greece',
    GT: 'Guatemala',
    GW: 'Guinea Bissau',
    GY: 'Guyana',
    HK: 'Hong Kong',
    HN: 'Honduras',
    HR: 'Croatia',
    HU: 'Hungaria',
    ID: 'Indonesia',
    IE: 'Ireland',
    IL: 'Israel',
    IN: 'India',
    IS: 'Iceland',
    IT: 'Italy',
    JM: 'Jamaica',
    JO: 'Jordan',
    JP: 'Japan',
    KE: 'Kenya',
    KG: 'Krygyzstan',
    KH: 'Cambodia',
    KN: 'Saint Kitts and Nevis',
    KR: 'South Korea',
    KW: 'Kuwait',
    KY: 'Cayman Islands',
    KZ: 'Kazakhstan',
    LA: 'Laos',
    LB: 'Lebanon',
    LC: 'Saint Lucia',
    LK: 'Sri Lanka',
    LR: 'Liberia',
    LT: 'Lithuania',
    LU: 'Luxembourg',
    LV: 'Latvia',
    MD: 'Moldova',
    MG: 'Madagascar',
    MK: 'Macedonia',
    ML: 'Mali',
    MN: 'Mongolia',
    MO: 'Macau',
    MR: 'Mauritania',
    MS: 'Montserrat',
    MT: 'Malta',
    MU: 'Mauritius',
    MW: 'Malawi',
    MX: 'Mexico',
    MY: 'Malaysia',
    MZ: 'Mozambique',
    NA: 'Namibia',
    NE: 'Niger',
    NG: 'Nigeria',
    NI: 'Nicaragua',
    NL: 'Netherlands',
    NP: 'Nepal',
    NO: 'Norway',
    NZ: 'New Zealand',
    OM: 'Oman',
    PA: 'Panama',
    PE: 'Peru',
    PG: 'Papua New Guinea',
    PH: 'Philippines',
    PK: 'Pakistan',
    PL: 'Poland',
    PT: 'Portugal',
    PW: 'Palau',
    PY: 'Paraguay',
    QA: 'Qatar',
    RO: 'Romania',
    RU: 'Russia',
    SA: 'Saudi Arabia',
    SB: 'Soloman Islands',
    SC: 'Seychelles',
    SE: 'Sweden',
    SG: 'Singapore',
    SI: 'Slovenia',
    SK: 'Slovakia',
    SL: 'Sierra Leone',
    SN: 'Senegal',
    SR: 'Suriname',
    ST: 'Sao Tome e Principe',
    SV: 'El Salvador',
    SZ: 'Swaziland',
    TC: 'Turks and Caicos Islands',
    TD: 'Chad',
    TH: 'Thailand',
    TJ: 'Tajikistan',
    TM: 'Turkmenistan',
    TN: 'Tunisia',
    TR: 'Turkey',
    TT: 'Republic of Trinidad and Tobago',
    TW: 'Taiwan',
    TZ: 'Tanzania',
    UA: 'Ukraine',
    UG: 'Uganda',
    US: 'United States of America',
    UY: 'Uruguay',
    UZ: 'Uzbekistan',
    VC: 'Saint Vincent and the Grenadines',
    VE: 'Venezuela',
    VG: 'British Virgin Islands',
    VN: 'Vietnam',
    YE: 'Yemen',
    ZA: 'South Africa',
    ZW: 'Zimbabwe',
};
